# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Action Lint

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Find yamls
        id: get_yamls
        run: |
          yamls="$(find .github/workflows -name "*.y*ml" | grep -v dependabot. | xargs echo)"
          echo "files=${yamls}" >> "$GITHUB_OUTPUT"

      - name: Action lint
        uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}
