# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Action Lint

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Find yamls
        id: get_yamls
        run: |
          yamls="$(find .github/workflows -name "*.y*ml" | grep -v dependabot. | xargs echo)"
          echo "files=${yamls}" >> "$GITHUB_OUTPUT"

      - name: Action lint
        uses: step-security/action-actionlint@3f6e745e8217d0acefffc87dc5cc4fefc3505207 # v1.66.1
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}
